begin;
-- Adds the per-tab analytics series so every admin chart shows a distinct cut
-- of the data instead of repeating the headline visit/collection totals.
create or replace function public.report_admin_overview(p_from date,p_to date) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_result jsonb;v_from timestamptz;v_to timestamptz;
begin
 if public.current_app_role()<>'admin' then raise exception 'forbidden' using errcode='42501';end if;
 if p_from is null or p_to is null or p_to<p_from or p_to-p_from>366 then raise exception 'invalid date range';end if;
 v_from:=p_from::timestamp at time zone 'Asia/Kolkata';v_to:=(p_to+1)::timestamp at time zone 'Asia/Kolkata';
 select jsonb_build_object(
  'total_visits',(select count(*) from public.visits where visit_date between p_from and p_to),
  'unique_patients',(select count(distinct patient_id) from public.visits where visit_date between p_from and p_to),
  'new_patients',(select count(*) from public.patients where created_at>=v_from and created_at<v_to),
  'op_collected_paise',(select coalesce(sum(p.amount_paise),0) from public.visit_payments p join public.visits v on v.id=p.visit_id where v.visit_date between p_from and p_to),
  'ip_collected_paise',(select coalesce(sum(amount_paise),0) from public.ip_payments where created_at>=v_from and created_at<v_to),
  'pharmacy_collected_paise',(select coalesce(sum(total_paise),0) from public.pharmacy_sales where source='op' and created_at>=v_from and created_at<v_to),
  'outstanding_paise',(select greatest(0,coalesce((select sum(fee_paise) from public.visits where visit_date between p_from and p_to),0)-coalesce((select sum(p.amount_paise) from public.visit_payments p join public.visits v on v.id=p.visit_id where v.visit_date between p_from and p_to),0)+coalesce((select sum(amount_paise) from public.ip_charges where created_at<v_to),0)-coalesce((select sum(amount_paise) from public.ip_payments where created_at<v_to),0))),
  'current_ip',(select count(*) from public.ip_tickets where status in ('admitted','discharge_pending')),
  'visits_by_day',(select coalesce(jsonb_agg(jsonb_build_object('date',metric_date,'visits',visits) order by metric_date),'[]'::jsonb) from (select visit_date as metric_date,count(*) as visits from public.visits where visit_date between p_from and p_to group by visit_date) q),
  'collections_by_day',(select coalesce(jsonb_agg(jsonb_build_object('date',metric_date,'op',op,'ip',ip,'pharmacy',pharmacy) order by metric_date),'[]'::jsonb) from (select d.metric_date,coalesce(o.amount,0) op,coalesce(i.amount,0) ip,coalesce(ph.amount,0) pharmacy from (select generate_series(p_from,p_to,'1 day')::date as metric_date)d left join (select v.visit_date as metric_date,sum(p.amount_paise) amount from public.visit_payments p join public.visits v on v.id=p.visit_id where v.visit_date between p_from and p_to group by v.visit_date)o on o.metric_date=d.metric_date left join (select (created_at at time zone 'Asia/Kolkata')::date as metric_date,sum(amount_paise) amount from public.ip_payments where created_at>=v_from and created_at<v_to group by 1)i on i.metric_date=d.metric_date left join (select (created_at at time zone 'Asia/Kolkata')::date as metric_date,sum(total_paise) amount from public.pharmacy_sales where source='op' and created_at>=v_from and created_at<v_to group by 1)ph on ph.metric_date=d.metric_date)q),
  'visits_by_doctor',(select coalesce(jsonb_agg(jsonb_build_object('doctor',display_name,'visits',visits) order by visits desc),'[]'::jsonb) from (select d.display_name,count(*) visits from public.visits v join public.doctors d on d.id=v.doctor_id where v.visit_date between p_from and p_to group by d.id,d.display_name order by visits desc limit 15)q),
  'ip_by_category',(select coalesce(jsonb_agg(jsonb_build_object('category',category,'amount_paise',amount) order by amount desc),'[]'::jsonb) from (select category,sum(amount_paise) amount from public.ip_charges where created_at>=v_from and created_at<v_to group by category)q),
  'top_medicines',(select coalesce(jsonb_agg(jsonb_build_object('medicine',medicine_name,'quantity',quantity) order by quantity desc),'[]'::jsonb) from (select pi.medicine_name,sum(si.quantity) quantity from public.pharmacy_sale_items si join public.prescription_items pi on pi.id=si.prescription_item_id join public.pharmacy_sales s on s.id=si.sale_id where s.created_at>=v_from and s.created_at<v_to group by pi.medicine_name order by quantity desc limit 10)q),
  -- OP tab: when patients actually arrive, and where the queue ends up.
  'visits_by_hour',(select coalesce(jsonb_agg(jsonb_build_object('hour',h.hour,'visits',coalesce(v.visits,0)) order by h.hour),'[]'::jsonb) from (select generate_series(0,23) as hour)h left join (select extract(hour from created_at at time zone 'Asia/Kolkata')::int as hour,count(*) visits from public.visits where visit_date between p_from and p_to group by 1)v on v.hour=h.hour),
  'visits_by_status',(select coalesce(jsonb_agg(jsonb_build_object('status',status,'visits',visits) order by visits desc),'[]'::jsonb) from (select status::text as status,count(*) visits from public.visits where visit_date between p_from and p_to group by status)q),
  -- Doctors tab: workload split between first consultations and follow-ups.
  'doctor_visit_mix',(select coalesce(jsonb_agg(jsonb_build_object('doctor',display_name,'op',op,'follow_up',follow_up) order by op+follow_up desc),'[]'::jsonb) from (select d.display_name,count(*) filter (where v.visit_type='op') op,count(*) filter (where v.visit_type='follow_up') follow_up from public.visits v join public.doctors d on d.id=v.doctor_id where v.visit_date between p_from and p_to group by d.id,d.display_name order by count(*) desc limit 12)q),
  -- IP tab: bed flow per day.
  'ip_flow_by_day',(select coalesce(jsonb_agg(jsonb_build_object('date',metric_date,'admissions',admissions,'discharges',discharges) order by metric_date),'[]'::jsonb) from (select d.metric_date,coalesce(a.total,0) admissions,coalesce(x.total,0) discharges from (select generate_series(p_from,p_to,'1 day')::date as metric_date)d left join (select (admission_at at time zone 'Asia/Kolkata')::date as metric_date,count(*) total from public.ip_tickets where admission_at>=v_from and admission_at<v_to group by 1)a on a.metric_date=d.metric_date left join (select (discharge_at at time zone 'Asia/Kolkata')::date as metric_date,count(*) total from public.ip_tickets where discharge_at>=v_from and discharge_at<v_to group by 1)x on x.metric_date=d.metric_date)q),
  -- Pharmacy tab: dispensing value and volume per day.
  'pharmacy_sales_by_day',(select coalesce(jsonb_agg(jsonb_build_object('date',metric_date,'amount_paise',amount,'items',items) order by metric_date),'[]'::jsonb) from (select d.metric_date,coalesce(s.amount,0) amount,coalesce(s.items,0) items from (select generate_series(p_from,p_to,'1 day')::date as metric_date)d left join (select (s.created_at at time zone 'Asia/Kolkata')::date as metric_date,sum(s.total_paise) amount,sum(i.quantity) items from public.pharmacy_sales s left join public.pharmacy_sale_items i on i.sale_id=s.id where s.created_at>=v_from and s.created_at<v_to group by 1)s on s.metric_date=d.metric_date)q),
  -- Collections tab: how money arrives, and what is still owed per source.
  'collections_by_mode',(select coalesce(jsonb_agg(jsonb_build_object('mode',mode,'amount_paise',amount) order by amount desc),'[]'::jsonb) from (select mode::text as mode,sum(amount) amount from (select p.mode,p.amount_paise amount from public.visit_payments p join public.visits v on v.id=p.visit_id where v.visit_date between p_from and p_to union all select mode,amount_paise from public.ip_payments where created_at>=v_from and created_at<v_to union all select payment_mode,total_paise from public.pharmacy_sales where source='op' and payment_mode is not null and created_at>=v_from and created_at<v_to)m group by mode)q),
  'source_balance',(select jsonb_build_array(
    jsonb_build_object('source','OP','collected_paise',(select coalesce(sum(p.amount_paise),0) from public.visit_payments p join public.visits v on v.id=p.visit_id where v.visit_date between p_from and p_to),'outstanding_paise',greatest(0,coalesce((select sum(fee_paise) from public.visits where visit_date between p_from and p_to),0)-coalesce((select sum(p.amount_paise) from public.visit_payments p join public.visits v on v.id=p.visit_id where v.visit_date between p_from and p_to),0))),
    jsonb_build_object('source','IP','collected_paise',(select coalesce(sum(amount_paise),0) from public.ip_payments where created_at>=v_from and created_at<v_to),'outstanding_paise',greatest(0,coalesce((select sum(amount_paise) from public.ip_charges where created_at>=v_from and created_at<v_to),0)-coalesce((select sum(amount_paise) from public.ip_payments where created_at>=v_from and created_at<v_to),0))),
    jsonb_build_object('source','Pharmacy','collected_paise',(select coalesce(sum(total_paise),0) from public.pharmacy_sales where source='op' and created_at>=v_from and created_at<v_to),'outstanding_paise',0))),
  -- Patients tab: first-time versus returning attendance per day.
  'patients_by_day',(select coalesce(jsonb_agg(jsonb_build_object('date',metric_date,'new_patients',new_patients,'returning_patients',returning_patients) order by metric_date),'[]'::jsonb) from (select d.metric_date,coalesce(q.new_patients,0) new_patients,coalesce(q.returning_patients,0) returning_patients from (select generate_series(p_from,p_to,'1 day')::date as metric_date)d left join (select v.visit_date as metric_date,count(distinct v.patient_id) filter (where (pt.created_at at time zone 'Asia/Kolkata')::date=v.visit_date) new_patients,count(distinct v.patient_id) filter (where (pt.created_at at time zone 'Asia/Kolkata')::date<v.visit_date) returning_patients from public.visits v join public.patients pt on pt.id=v.patient_id where v.visit_date between p_from and p_to group by v.visit_date)q on q.metric_date=d.metric_date)q)
 ) into v_result;
 return v_result;
end $$;
revoke all on function public.report_admin_overview(date,date) from public;
grant execute on function public.report_admin_overview(date,date) to authenticated;
commit;
